# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# Zinit plugin manager
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
if [ ! -d "$ZINIT_HOME" ]; then
   mkdir -p "$(dirname $ZINIT_HOME)"
   git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi
source "${ZINIT_HOME}/zinit.zsh"
unalias zi 2>/dev/null  # Free up 'zi' for zoxide interactive

# Zinit plugins
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab
zinit light jeffreytse/zsh-vi-mode

# Keybindings
bindkey '^y' autosuggest-accept    # Ctrl+Y to accept autosuggestion

# Completion settings
autoload -Uz compinit && compinit
# Case-insensitive, partial-word, and substring completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
# Disable default menu, use fzf-tab instead
zstyle ':completion:*' menu no
# Preview directory contents when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'

# ZSH options
setopt AUTO_CD              # cd into directory by typing its name
setopt AUTO_PUSHD           # Push directories onto stack
setopt PUSHD_IGNORE_DUPS    # Don't push duplicates

# Starship prompt
eval "$(starship init zsh)"

# Atuin (shell history)
eval "$(atuin init zsh)"

# fnm (Fast Node Manager)
eval "$(fnm env --use-on-cd)"

# zoxide (smarter cd)
eval "$(zoxide init --cmd cd zsh)"

# Editor
export EDITOR="nvim"
export VISUAL="nvim"

# Aliases - eza (modern ls)
alias l='eza --icons'
alias ll='eza -la --icons'
alias la='eza -la --icons'
alias lt='eza --tree --icons'
alias lg='eza -la --git --icons'

# Aliases - General
alias a='eza -la --icons --sort=modified'
alias c='clear'
alias e='nvim'
alias cdd='cd ~/.dotfiles'

# Aliases - Git
alias g='git'
alias gi='git init .'
alias ga='git add'
alias gl='git log'
alias g1='git log --oneline'
alias gpl='git pull'
alias gph='git push'
alias gd='git diff'
alias gc='git commit'
alias gca='git commit -a'
alias gco='git checkout'
alias gb='git branch'
alias gs='git status'
